@host = http://localhost:5003

###
GET {{host}}/v1/api/order-state-machine HTTP/1.1
content-type: application/json

###
POST {{host}}/v1/api/order HTTP/1.1
content-type: application/json

{
    "customerId": "c576e54a-59a1-4a68-9da3-53f96f88d3ff",
    "orderDate": "2021-09-15T19:01:55.714942+03:00",
    "requiredDate": "2021-09-15T19:01:55.714942+03:00"
}

# provide items which has been bought
# provide ship information

###
@orderId = 148a21fd-0f75-4936-b1ee-be3514dfda60
# GET {{host}}/v1/api/order/{{orderId}}/status HTTP/1.1
# content-type: application/json

###
POST {{host}}/v1/api/payment HTTP/1.1
content-type: application/json

{
    "orderId": "{{orderId}}",
    "customerId": "c576e54a-59a1-4a68-9da3-53f96f88d3ff",
    "transactionId": "c576e54a-59a1-4a68-9da3-53f96f88d3ff",
    "failedAt": "PAYMENT_FAILED1"
}

###
POST {{host}}/v1/api/shipment/{{orderId}}/pick HTTP/1.1
content-type: application/json

{
    "orderId": "{{orderId}}",
    "shipperId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "customerId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "beFailedAt": "Dispatched"
}

###
POST {{host}}/v1/api/shipment/{{orderId}}/delivery HTTP/1.1
content-type: application/json

{
    "orderId": "{{orderId}}",
    "shipperId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "customerId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "beFailedAt": "Delivered1"
}