@host = http://localhost:5003

###
GET {{host}}/v1/api/order-state-machine HTTP/1.1
content-type: application/json

###
POST {{host}}/v1/api/order HTTP/1.1
content-type: application/json

{
    "customerId": "50f51e5f-36c6-4582-b428-ac15d70d9012",
    "orderDate": "2021-09-15T19:01:55.714942+03:00",
    "requiredDate": "2021-09-15T19:01:55.714942+03:00",
    "details": [
        {
            "productId": "88a6d251-d2ba-420a-822b-8c68ec9ce4eb",
            "unitPrice": 1000,
            "quantity": 1
        }
    ],
    "failedAt": "VALIDATION_FAILED1"
}

# todo: provide ship information

###
@orderId = 5934aac6-c52a-4aaa-9243-742bcc24126c
# GET {{host}}/v1/api/order/{{orderId}}/status HTTP/1.1
# content-type: application/json

###
POST {{host}}/v1/api/payment HTTP/1.1
content-type: application/json

{
    "orderId": "{{orderId}}",
    "customerId": "c576e54a-59a1-4a68-9da3-53f96f88d3ff",
    "transactionId": "c576e54a-59a1-4a68-9da3-53f96f88d3ff",
    "failedAt": "PAYMENT_FAILED1"
}

###
POST {{host}}/v1/api/shipment/{{orderId}}/pick HTTP/1.1
content-type: application/json

{
    "orderId": "{{orderId}}",
    "shipperId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "customerId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "beFailedAt": "Dispatched1"
}

###
POST {{host}}/v1/api/shipment/{{orderId}}/delivery HTTP/1.1
content-type: application/json

{
    "orderId": "{{orderId}}",
    "shipperId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "customerId": "008765f8-3e46-4491-b3b4-c22fe1da9968",
    "beFailedAt": "Delivered1"
}