@host = http://localhost:5010

###
GET {{host}}/product-api/v1/products HTTP/1.1
content-type: application/json
x-query: {"filters":[],"sorts":["NameDesc"]}

###
POST {{host}}/product-api/v1/products HTTP/1.1
content-type: application/json

{
  "name": "test product 1"
}

###
@productUpdateId = 942c835c-4fae-4819-8994-e2db7445d92c
PUT {{host}}/product-api/v1/products/{{productUpdateId}} HTTP/1.1
content-type: application/json

{
  "name": "test product 123"
}

###
@productDeleteId = 942c835c-4fae-4819-8994-e2db7445d92c
DELETE  {{host}}/product-api/v1/products/{{productDeleteId}} HTTP/1.1
content-type: application/json
