@host = http://localhost:5002

###
GET {{host}}/api/v1/products HTTP/1.1
content-type: application/json
x-query: {"filters":[],"sorts":["NameDesc"]}

###
POST {{host}}/api/v1/products HTTP/1.1
content-type: application/json

{
  "name": "test product"
}

###
@productUpdateId = b528123b-9bd8-4583-b778-d73a6cc7b81a
PUT {{host}}/api/v1/products/{{productUpdateId}} HTTP/1.1
content-type: application/json

{
  "name": "test product 123"
}

###
@productDeleteId = b528123b-9bd8-4583-b778-d73a6cc7b81a
DELETE  {{host}}/api/v1/products/{{productDeleteId}} HTTP/1.1
content-type: application/json
