// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Shipping
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var shipperInfo = ShipperInfoEntityType.Create(this);
            var shippingOrder = ShippingOrderEntityType.Create(this);
            var state = StateEntityType.Create(this);

            ShippingOrderEntityType.CreateForeignKey1(shippingOrder, shipperInfo);

            ShipperInfoEntityType.CreateAnnotations(shipperInfo);
            ShippingOrderEntityType.CreateAnnotations(shippingOrder);
            StateEntityType.CreateAnnotations(state);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
