// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Northwind.IntegrationEvents
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ProductCreated : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProductCreated"",""namespace"":""Northwind.IntegrationEvents"",""fields"":[{""name"":""ProductId"",""type"":""string""},{""name"":""ProductName"",""type"":""string""},{""name"":""CategoryId"",""type"":[""null"",""string""]},{""name"":""CategoryName"",""type"":[""null"",""string""]},{""name"":""SupplierId"",""type"":[""null"",""string""]},{""name"":""SupplierName"",""type"":[""null"",""string""]}]}");
		private string _ProductId;
		private string _ProductName;
		private string _CategoryId;
		private string _CategoryName;
		private string _SupplierId;
		private string _SupplierName;
		public virtual Schema Schema
		{
			get
			{
				return ProductCreated._SCHEMA;
			}
		}
		public string ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				this._ProductName = value;
			}
		}
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				this._CategoryId = value;
			}
		}
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				this._CategoryName = value;
			}
		}
		public string SupplierId
		{
			get
			{
				return this._SupplierId;
			}
			set
			{
				this._SupplierId = value;
			}
		}
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				this._SupplierName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductId;
			case 1: return this.ProductName;
			case 2: return this.CategoryId;
			case 3: return this.CategoryName;
			case 4: return this.SupplierId;
			case 5: return this.SupplierName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductId = (System.String)fieldValue; break;
			case 1: this.ProductName = (System.String)fieldValue; break;
			case 2: this.CategoryId = (System.String)fieldValue; break;
			case 3: this.CategoryName = (System.String)fieldValue; break;
			case 4: this.SupplierId = (System.String)fieldValue; break;
			case 5: this.SupplierName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
