// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace HumanResources
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var employeeTerritory = EmployeeTerritoryEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var addressInfo = AddressInfoEntityType.Create(this);
            var employee = EmployeeEntityType.Create(this);
            var addressInfo0 = AddressInfo0EntityType.Create(this);
            var region = RegionEntityType.Create(this);
            var shipper = ShipperEntityType.Create(this);
            var supplier = SupplierEntityType.Create(this);
            var addressInfo1 = AddressInfo1EntityType.Create(this);
            var territory = TerritoryEntityType.Create(this);

            EmployeeTerritoryEntityType.CreateForeignKey1(employeeTerritory, employee);
            EmployeeTerritoryEntityType.CreateForeignKey2(employeeTerritory, territory);
            AddressInfoEntityType.CreateForeignKey1(addressInfo, customer);
            EmployeeEntityType.CreateForeignKey1(employee, employee);
            AddressInfo0EntityType.CreateForeignKey1(addressInfo0, employee);
            AddressInfo1EntityType.CreateForeignKey1(addressInfo1, supplier);
            TerritoryEntityType.CreateForeignKey1(territory, region);

            EmployeeEntityType.CreateSkipNavigation1(employee, territory, employeeTerritory);
            TerritoryEntityType.CreateSkipNavigation1(territory, employee, employeeTerritory);

            EmployeeTerritoryEntityType.CreateAnnotations(employeeTerritory);
            CustomerEntityType.CreateAnnotations(customer);
            AddressInfoEntityType.CreateAnnotations(addressInfo);
            EmployeeEntityType.CreateAnnotations(employee);
            AddressInfo0EntityType.CreateAnnotations(addressInfo0);
            RegionEntityType.CreateAnnotations(region);
            ShipperEntityType.CreateAnnotations(shipper);
            SupplierEntityType.CreateAnnotations(supplier);
            AddressInfo1EntityType.CreateAnnotations(addressInfo1);
            TerritoryEntityType.CreateAnnotations(territory);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0-rc.2.21480.5");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
