// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ProductCatalog
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var productOutbox = ProductOutboxEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var supplierInfo = SupplierInfoEntityType.Create(this);

            ProductEntityType.CreateForeignKey1(product, category);
            ProductEntityType.CreateForeignKey2(product, supplierInfo);

            CategoryEntityType.CreateAnnotations(category);
            ProductOutboxEntityType.CreateAnnotations(productOutbox);
            ProductEntityType.CreateAnnotations(product);
            SupplierInfoEntityType.CreateAnnotations(supplierInfo);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0-rc.2.21480.5");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
