// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CustomerService
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var customerCustomerDemo = CustomerCustomerDemoEntityType.Create(this);
            var customerDemographic = CustomerDemographicEntityType.Create(this);
            var customerInfo = CustomerInfoEntityType.Create(this);

            CustomerCustomerDemoEntityType.CreateForeignKey1(customerCustomerDemo, customerDemographic);

            CustomerCustomerDemoEntityType.CreateAnnotations(customerCustomerDemo);
            CustomerDemographicEntityType.CreateAnnotations(customerDemographic);
            CustomerInfoEntityType.CreateAnnotations(customerInfo);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
